language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

install:
  - pip install -r requirements.txt

script:
  - coverage run -m pytest

after_success:
  - coverage report